/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Pacientes.Paciente;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author juanb
 */
public class GUI extends javax.swing.JFrame {
    
    static int contador = 0;
    static ArrayList<Paciente> registroPacientes;
    
    //Para la opción de tipo de pacientes al presionar el botón de Registrar Paciente
    String[] tiposPaciente = {
    
          "Paciente cotizante",
          "Paciente beneficiario"
    };
    
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtReporte = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaReporte = new javax.swing.JTextArea();
        txtSeleccioneUnaOpcion = new javax.swing.JLabel();
        botonRegistrarPaciente = new javax.swing.JButton();
        botonRegistrarServicioPaciente = new javax.swing.JButton();
        botonBuscarPaciente = new javax.swing.JButton();
        botonMostrarRegistroPacientes = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        txtRegimenContributivoDeSalud = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtReporte.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        txtReporte.setText("Reporte:");

        txtAreaReporte.setColumns(20);
        txtAreaReporte.setRows(5);
        txtAreaReporte.setEnabled(false);
        jScrollPane1.setViewportView(txtAreaReporte);

        txtSeleccioneUnaOpcion.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        txtSeleccioneUnaOpcion.setText("Seleccione una opcion:");

        botonRegistrarPaciente.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        botonRegistrarPaciente.setText("Registrar a un paciente");
        botonRegistrarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarPacienteActionPerformed(evt);
            }
        });

        botonRegistrarServicioPaciente.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        botonRegistrarServicioPaciente.setText("Registrar un servicio a un paciente");
        botonRegistrarServicioPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarServicioPacienteActionPerformed(evt);
            }
        });

        botonBuscarPaciente.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        botonBuscarPaciente.setText("Buscar a un paciente");

        botonMostrarRegistroPacientes.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        botonMostrarRegistroPacientes.setText("Mostrar a todos los pacientes registrados");

        botonSalir.setFont(new java.awt.Font("Trebuchet MS", 3, 16)); // NOI18N
        botonSalir.setForeground(new java.awt.Color(204, 0, 0));
        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        txtRegimenContributivoDeSalud.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        txtRegimenContributivoDeSalud.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtRegimenContributivoDeSalud.setText("Regimen contributivo de salud");
        txtRegimenContributivoDeSalud.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSeleccioneUnaOpcion)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtReporte)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtRegimenContributivoDeSalud, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(166, 166, 166))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botonRegistrarPaciente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botonRegistrarServicioPaciente)
                                .addGap(18, 18, 18)
                                .addComponent(botonBuscarPaciente)
                                .addGap(18, 18, 18)
                                .addComponent(botonMostrarRegistroPacientes)
                                .addGap(18, 18, 18)))
                        .addComponent(botonSalir)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtRegimenContributivoDeSalud)
                .addGap(69, 69, 69)
                .addComponent(txtSeleccioneUnaOpcion)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonRegistrarPaciente)
                    .addComponent(botonRegistrarServicioPaciente)
                    .addComponent(botonBuscarPaciente)
                    .addComponent(botonMostrarRegistroPacientes)
                    .addComponent(botonSalir))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtReporte)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Funciona para darle un acción/evento al botón escogido:
    
    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        
        int resp = JOptionPane.showConfirmDialog(null, "¿Esta seguro que desea salir del programa?", "Alerta", JOptionPane.YES_NO_OPTION);
        
        System.exit(0);
        
    }//GEN-LAST:event_botonSalirActionPerformed
    
     // Funciona para darle un acción/evento al botón escogido:
    
    private void botonRegistrarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarPacienteActionPerformed

        //Ventana emergente que aparece al presionar el botón, dandole la opción de escoger al usuario el tipo de paciente a registrar
        
        String resp = (String) JOptionPane.showInputDialog(null, "Seleccione el tipo de paciente a registrar", "Tipo de paciente", JOptionPane.DEFAULT_OPTION, null, tiposPaciente, tiposPaciente[0]);
        
    }//GEN-LAST:event_botonRegistrarPacienteActionPerformed
     
     // Funciona para darle un acción/evento al botón escogido:
    
    
    private void botonRegistrarServicioPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarServicioPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRegistrarServicioPacienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscarPaciente;
    private javax.swing.JButton botonMostrarRegistroPacientes;
    private javax.swing.JButton botonRegistrarPaciente;
    private javax.swing.JButton botonRegistrarServicioPaciente;
    private javax.swing.JButton botonSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAreaReporte;
    private javax.swing.JLabel txtRegimenContributivoDeSalud;
    private javax.swing.JLabel txtReporte;
    private javax.swing.JLabel txtSeleccioneUnaOpcion;
    // End of variables declaration//GEN-END:variables
}
